### ISSUE TITLE
Date parsing not correct

### ISSUE THREAD

**Issue by jhihn** [DataGarage/node-xls-json#9]
I have a date of 05/31/1993 in my xls an it keeps coming out as 5/30/1989.
I checked it against the xlsjs demo utility, it parses the date correctly there. It's only in xls-to-json that the  problem manifests.

Any idea why this would be?

**Comment by rodrigograca31** [comment]
I guess this isn't an issue anymore? (2015....)

**Comment by jhihn** [comment]
I'd say it's still an issue, but I have a work around. Why wouldn't you want to fix it for other users? I'd also like to remove my work around

**Comment by rodrigograca31** [comment]
I do want it to be fixed for others, was trying to clean out old issues and thought this had been solved over the last 3 years...

are you using the latest version? probably not... please try to use it and see if the issue still exists, since this package dependencies were updated to the latest and greatest a few months ago...

let me know and I will reopen the issue :)
